apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-automation-tool
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-automation-tool
  template:
    metadata:
      labels:
        app: kubernetes-automation-tool
    spec:
      containers:
        - name: kubernetes-automation-tool
          image: IMAGE_TAG # This will be replaced during deployment
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: FLASK_ENV
              value: "production"
            - name: KUBECONFIG
              value: "/root/.kube/config"
          volumeMounts:
            - name: kube-config
              mountPath: "/root/.kube"
      volumes:
        - name: kube-config
          secret:
            secretName: kube-config-secret

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-automation-tool-service
  namespace: default
spec:
  selector:
    app: kubernetes-automation-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
